name: pypi_publish
on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install Pip and Setuptools
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools==60.6.0 wheel==0.37.1 pylint==2.10.2
      - uses: bazelbuild/setup-bazelisk@v1
      - name: Bazel build
        run: bazel build //...
      - name: Packing
        run: |
          mkdir dist package_build
          echo "Ref name: ${GITHUB_REF_NAME}"
          ./package/build_pip.sh "${GITHUB_REF_NAME}" "$(pwd)/package_build" "$(pwd)/dist"
      - name: Publish package to TEST
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPY_TEST_API_TOKEN }}
          verbose: true
          repository_url: https://test.pypi.org/legacy/
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
